version: '3'
services:
    php-apache:
        image: php:apache-buster
        ports:
            - 80:80
        volumes:
            - wordpress:/var/www/html
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Minsk"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

volumes:
    mariadb:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /var/jenkins/mysql
    wordpress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /var/jenkins/wordpress
